import serial

ser = serial.Serial('COM3')

print('端口名： ' + ser.name)
print('端口： ' + ser.port)
print()

print('串口默认配置：')
print('baudrate 波特率： ' + str(ser.baudrate))
print('bytesize 位宽： ' + str(ser.bytesize))
print('parity 校验位： ' + str(ser.parity))
print('stopbits 停止位： ' + str(ser.stopbits))
print('timeout 读超时： ' + str(ser.timeout))
print('writeTimeout 写超时： ' + str(ser.writeTimeout))
print('xonxoff 软件流控： ' + str(ser.xonxoff))
print('rtscts 硬件流控 RTS： ' + str(ser.rtscts))
print('dsrdtr 硬件流控 CTS： ' + str(ser.dsrdtr))
print('interCharTimeout 字符间隔超时： ' + str(ser.interCharTimeout))

# ser.open()
ser.flushOutput()
# ser.reset_output_buffer()
ser.write(b'hello\r\n')
ser.write(b'hello\r\n')
ser.write(b'hello\r\n')
ser.write(b'hello\r\n')
ser.write(b'hello\r\n')
ser.write(b'hello\r\n')
ser.close()